config/routes.rb
Rails.application.routes.draw do
  get 'make/browse'

  get 'home/index'

  devise_for :users

  root 'home#index'

  get 'stats' => 'home#stats'
  get 'browse' => 'make#browse'

end

app/models/bus.rb
class Bus < ActiveRecord::Base
  belongs_to :network_def
  has_many :messages
end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
  belongs_to :multiplex
  belongs_to :node_ref
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :network_def
end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :label_set
end

app/models/label_set.rb
class LabelSet < ActiveRecord::Base
  belongs_to :multiplex
  has_many :labels
  has_many :label_groups
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :network_def
  has_many :years
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :models, :dependent => :destroy
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :bus
  has_one :note
  has_one :producer
  has_many :can_signals
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :make
  has_many :years, :dependent => :destroy
end

app/models/multiplex.rb
class Multiplex < ActiveRecord::Base
  belongs_to :message
  has_many :mux_groups
  has_one :note
  has_one :consumer
  has_one :value
  has_one :label_set
end

app/models/mux_group.rb
class MuxGroup < ActiveRecord::Base
  belongs_to :multiplex
  has_many :can_signals
end

app/models/node.rb
class Node < ActiveRecord::Base
  belongs_to :network_def
  has_one :var
end

app/models/node_ref.rb
class NodeRef < ActiveRecord::Base
  belongs_to :producer
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :var
  belongs_to :multiplex
end

app/models/producer.rb
class Producer < ActiveRecord::Base
  belongs_to :message_id
  has_many :node_refs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :votes
end

app/models/value.rb
class Value < ActiveRecord::Base
  belongs_to :var
  belongs_to :multiplex
  belongs_to :can_signal
end

app/models/var.rb
class Var < ActiveRecord::Base
  belongs_to :node
  has_one :note
  has_one :value
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :can_signal
  belongs_to :user
end

app/models/year.rb
class Year < ActiveRecord::Base
  belongs_to :model
  has_one :network_def
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="og_title">Open Garage's</div>
<div id="home_title">Signal Explorer</div>

<div id="search_vehicle_type">Search Vehicle Type</div>
<div id="std_link"><%= link_to 'Browse Vehicles', browse_path %></div>
<div id="std_link"><%= link_to 'View Stats', stats_path %></div>

app/views/home/stats.html.erb
<div id="seciton_title">Stats</div>
<div id=statbox>
 <div id=vehicle_stats>
   <div id=vehicle_stat_label>Number of Makes</div>&nbsp<div id=stat_value><%= Make.all.count %></div>
   <div id=vehicle_stat_label>Number of Models</div>&nbsp<div id=stat_value><%= Model.all.count %></div>
   <div id=vehicle_stat_label>Number of Model Years</div>&nbsp<div id=stat_value><%= Year.all.count %></div>
   <div id=vehicle_stat_label>Number of Messages</div>&nbsp<div id=stat_value><%= Message.all.count %></div>
   <div id=vehicle_stat_label>Number of Signals</div>&nbsp<div id=stat_value><%= CanSignal.all.count %></div>
 </div>
</div>
<div id=user_stats>
  <div id=user_high_submission_label>Highest Submissions</div>
  <div id=user_stat_column>
    <div id=user_stat_name>TODO</div>
  </div>
  <div id=user_high_quality_label>Highest Rankings</div>
  <div id=user_stat_column>
    <div id=user_stat_name>TODO</div>
  </div>
</div>
<%= link_to 'Back', home_index_path %>